Update 0002
bs-community/rfcs pull request #4
Opened 2020-08-17 14:21 UTC by tnqzh123

修改 API 细节。

2020-08-17 14:42 UTC, g-plane reviewed
这个应该算是只影响内部的 API 吧？给外部使用的 API 应该是不受影响的，可以的话，最好分开说明。

2020-08-17 19:19 UTC, tnqzh123 commented
「分开说明」是指？

我觉得改动的 API 应该也是可以提供给外部使用的？

这些改动只是 API 地址变更了，完善了一点细节的说明（实际上和更改之前是一样的）。

2020-08-17 23:04 UTC, g-plane commented
给外部使用的 API 不要改变。

2020-08-19 09:54 UTC, g-plane commented
可以考虑根据现有的路由进行类似的改动：

https://github.com/bs-community/blessing-skin-server/blob/bf860d6a68171deb0fd172633a2fdcf2c3a8678d/routes/web.php#L90-L101

同时 `/api/textures/{tid}/desc` 作为对外部开放使用的 API 不需要也尽量不要变动。

2020-08-20 23:49 UTC, g-plane commented on rfcs/0002-textures-desc.md
> +#### 内部使用的 API
这一行是不是多余的？

2020-08-21 01:51 UTC, g-plane requested changes

2020-08-21 01:51 UTC, g-plane commented on rfcs/0002-textures-desc.md
>  GET /textures/{tid}/desc
```suggestion
GET /texture/{tid}/desc
```

2020-08-21 01:51 UTC, g-plane commented on rfcs/0002-textures-desc.md
>  PUT /textures/{tid}/desc
```suggestion
PUT /texture/{tid}/desc
```

2020-08-21 10:37 UTC, g-plane approved these changes

2020-08-21 10:37 UTC, merged